format = """
$username\
$directory\
$git_branch\
$git_status\
$fill\
$python\
$cpp\
$elixir\
$java\
$nodejs\
$rust\
$golang\
$bun\
$ruby\
$haskell\
$c\
$kotlin\
$mojo\
$dotnet\
$zig\
$solidity\
$deno\
$aws\
$package\
$docker_context\
$kubernetes\
$helm\
$terraform\
$jobs\
$line_break\
$character"""

add_newline = true
palette = 'nord'
command_timeout = 1000
scan_timeout = 1000

[username]
style_user = 'bold blue'
style_root = 'black bold'
format = '[$user]($style) '
disabled = false
show_always = true
aliases = { "corpuser034g" = "matchai" }

[directory]
style = 'bold fg:dark_blue'
format = '[$path ]($style)'
truncation_length = 3
truncation_symbol = '…/'
truncate_to_repo = false

[git_status]
deleted = ''

[fill]
symbol = ' '

[python]
symbol = ' '
style = 'yellow'
format = '[${symbol}${pyenv_prefix}(${version} )(\($virtualenv\) )]($style)'
pyenv_version_name = true
pyenv_prefix = ''

[cpp]
symbol = ' '
style = 'blue'

[elixir]
symbol = ' '
style = 'purple'

[nodejs]
symbol = ' '
style = 'green'

[golang]
symbol = ' '
style = 'teal'

[bun]
symbol = ' '
style = 'green'

[ruby]
symbol = ' '
style = 'red'

[haskell]
symbol = ' '
style = 'purple'

[c]
symbol = ' '
style = 'blue'

[kotlin]
symbol = ' '
style = 'purple'

[mojo]
symbol = ' '
style = 'orange'

[dotnet]
symbol = ' '
style =  'purple'

[zig]
symbol = ' '
style = 'yellow'

[rust]
symbol = '󱘗 '
style = 'orange'

[java]
symbol = ' '
style = 'red'

[solidity]
symbol = ' '
style = 'grey'

[deno]
symbol = ' '
style = 'green'

[package]
symbol = '󰏗 '
style = 'teal'

[aws]
symbol = ' '
style = 'yellow'
format = '[$symbol($profile )(\[$duration\] )]($style)'

[docker_context]
symbol = ' '
style = 'fg:#06969A'
format = '[$symbol]($style) $path'
detect_files = ['docker-compose.yml', 'docker-compose.yaml', 'Dockerfile']
detect_extensions = ['Dockerfile']

[kubernetes]
symbol = ' '
style = 'blue'

[helm]
symbol = ' '
style = 'teal'

[terraform]
symbol = ' '
style = 'purple'

[jobs]
symbol = ' '
style = 'red'
number_threshold = 1
format = '[$symbol]($style)'

[palettes.nord]
dark_blue = '#5E81AC'
blue = '#81A1C1'
teal = '#88C0D0'
red = '#BF616A'
orange = '#D08770'
green = '#A3BE8C'
yellow = '#EBCB8B'
purple = '#B48EAD'
gray = '#434C5E'
black = '#2E3440'
white='#D8DEE9'
